### ISSUE TITLE
[imio/helm-plausible-analytics] wrong indentation initialDelaySeconds

### ISSUE THREAD

**Issue by mpas97** [IMIO/helm-plausible-analytics#19]
When doing helm upgrade, I get:
```
warnings.go:70] unknown field "spec.template.spec.containers[0].livenessProbe.httpGet.initialDelaySeconds
warnings.go:70] unknown field "spec.template.spec.containers[0].readinessProbe.httpGet.initialDelaySeconds"
```

In the values file we have
```
livenessProbe:
  httpGet:
    path: /
    port: http
    initialDelaySeconds: 30
```

Although it should be something like this:
```
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
```

Using current chart version: 0.3.0
