### ISSUE TITLE
[imio/helm-plausible-analytics] allow setting additional volumes and their mounts

### ISSUE THREAD

**Issue by vittoriocanilli** [IMIO/helm-plausible-analytics#25]
**Is your feature request related to a problem? Please describe.**
I am creating my secret with all environment variables (used in the `secret.existingSecret` value) with [Secret provider class for Azure Key vaults](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master), which requires an additional volume in the deployment with a specific path. As I can not define such volume, the secret provider class cannot create the corresponding secret.

**Describe the solution you'd like**
I would need new values that allow to create additional volumes and their mounts like this:
```yaml
volumes: []
# - name: my_volume
#   secret:
#     secretName: my_secret
#     optional: false

volumeMounts: []
# - name: mounted_secret
#   mountPath: "/etc/mounted_secret"
#   readOnly: true
```

**Describe alternatives you've considered**
At the moment I am creating the secret manually locally and I apply it: it works, but it is quite cumbersome.

**Additional context**
I noticed another issue which would benefit by having the chance to define additional volumes and their mounts: https://github.com/IMIO/helm-plausible-analytics/issues/12
