### ISSUE TITLE
[imio/helm-plausible-analytics] define database password from Kubernetes secret

### ISSUE THREAD

**Issue by vittoriocanilli** [IMIO/helm-plausible-analytics#26]
**Is your feature request related to a problem? Please describe.**
It is nice that this chart allows to set up the PostgreSQL and ClickHouse databases from scratch, but I would prefer not to define their passwords directly in the values file, as I am committing the file with the edited values in a repository.  I am using the version `0.4.0` of this chart and currently the database passwords need to be defined as follows:
```yaml
postgresql:
  auth:
    password: "myPostgreSqlPwd"
clickhouse:
  auth:
    password: "myClickHousePwd"
```

**Describe the solution you'd like**
It would be better if the password could be set from a Kubernetes secret as follows:
```yaml
postgresql:
  auth:
    passwordSecretName: "secret-on-kubernetes"
    passwordSecretKey: "postgresql-password"
clickhouse:
  auth:
    passwordSecretName: "secret-on-kubernetes"
    passwordSecretKey: "clickhouse-password"
```

**Describe alternatives you've considered**
Currently I am still using the default passwords, because I am still in an initial phase of my Plausible's setup; without this feature being implemented, I have considered setting up the databases with other Helm chart and using this one only for Plausible, as follows:
```yaml
postgresql:
  enabled: false
clickhouse:
  enabled: false
```

**Additional context**

**Comment by alexnuttinck** [comment]
Hi @vittoriocanilli,

Check the documentation about the [postgresql](https://github.com/bitnami/charts/tree/main/bitnami/postgresql#postgresql-common-parameters) and [clickhouse](https://github.com/bitnami/charts/tree/main/bitnami/clickhouse#clickhouse-parameters) charts from bitnami.

They allow you to define an existing secret. (with the `auth.existingSecret` parameter).

**Comment by vittoriocanilli** [comment]
Hi @alexnuttinck,

thanks for your answer! I have noticed that the bitnami's charts for PostgreSQL and ClickHouse are dependencies of this chart. Does it mean that I can use their values within the blocks `postgresql` and  `clickhouse` of this chart respectively?

If yes, I could already achieve my goal by setting the following values:

```yaml
postgresql:
  auth:
    existingSecret: "secret-on-kubernetes"
    secretKeys: 
      userPasswordKey: "postgresql-password"
clickhouse:
  auth:
    existingSecret: "secret-on-kubernetes"
    existingSecretKey: "clickhouse-password"
```

**Comment by vittoriocanilli** [comment]
It looks like I can indeed use the Bitnami's charts values within the blocks `postgresql` and `clickhouse` of this chart respectively.
After some tests I have found how to achieve my goal (slightly differently than in my previous message):

```yaml
postgresql:
  auth:
    existingSecret: "secret-on-kubernetes"
    secretKeys: 
      adminPasswordKey: "postgresql-password"
clickhouse:
  auth:
    existingSecret: "secret-on-kubernetes"
    existingSecretKey: "clickhouse-password"
```

I am closing the issue as it is solved 😄
