### ISSUE TITLE
[imio/helm-plausible-analytics] ClickHouse with multiple replicas and shards

### ISSUE THREAD

**Issue by vittoriocanilli** [IMIO/helm-plausible-analytics#27]
I am setting up Plausible with ClickHouse having multiple replicas and shards: 

```yaml
clickhouse:
 auth:
    username: plausible_user
    password: plausible_password
    database: plausible_events_db
  shards: 2
  replicaCount: 3
  resourcesPreset: "medium"
  pdb:
    create: true
    maxUnavailable: 1
  zookeeper:
    enabled: true
    replicaCount: 3
    resourcesPreset: "small"
    pdb:
      create: true
      maxUnavailable: 1
```

I am using the headless endpoint `http://plausible_user:plausible_password@plausible-analytics-clickhouse-headless.<namespace>:8123/plausible_events_db`  as `CLICKHOUSE_DATABASE_URL` and everything seems to work.

When I try to delete one of the ClickHouse pods to simulate what would happen during a rescheduling through the Kubernetes cluster's nodes, the pod gets recreated correctly, but the data on the sites on my Plausible dashboard is no more consistent as before: sometimes the graphs have data, sometimes they are empty, sometimes they are not rendered because of a HTTP 500 error.

In this chart's default values I see that you use only one replica and one shard for ClickHouse:

```yaml
clickhouse:
  shards: 1
  replicaCount: 1
```

mentioning a [Plausible discussion](https://github.com/plausible/analytics/discussions/1603) to highlight that Plausible does not support clusters.

I am quite new with ClickHouse: does that actually mean that Plausible can only run with ClickHouse if it has one shard and one replica? Just to understand if it is a limitation of Plausible or of this chart. Thanks in advance.
